---
# Namespace untuk aplikasi
apiVersion: v1
kind: Namespace
metadata:
  name: todo-app
  labels:
    environment: production
    managed-by: argocd

---
# Service Account dengan Workload Identity annotation
# Email SA harus sesuai output Terraform: app_service_account_email
apiVersion: v1
kind: ServiceAccount
metadata:
  name: todo-app-sa
  namespace: todo-app
  annotations:
    iam.gke.io/gcp-service-account: "todo-app-sa@project-741337ff-4507-4f1d-8f6.iam.gserviceaccount.com"

---
# Namespace untuk tools DevOps
apiVersion: v1
kind: Namespace
metadata:
  name: devops
  labels:
    purpose: cicd

---
apiVersion: v1
kind: Namespace
metadata:
  name: argocd
  labels:
    purpose: gitops
